### ISSUE TITLE
design enclosure

### ISSUE THREAD

**Issue by wir19** [penk/penkesu#1]
0. Please look at old Psion 5 keyboard and hiding it under screen.

1. In my opinion second idea are waterproof box enclosure similar normal army box. 

2. is possible add some keys near screen? turn off wifi, decrease speed cpu, speed memory etc.

meybe add solar panel on top for increase working time?

**Comment by wir19** [comment]
![aaaaaaa](https://user-images.githubusercontent.com/95350646/153928891-6e058c5f-7f51-49ba-b42b-5b73d5604abc.jpg)
system delete prev upload.

**Comment by penk** [comment]
@wir19 thank you for your suggestions, this is an open source project, so please feel free to modify the design and make it yours. :-)
