### ISSUE TITLE
Keyboard connection

### ISSUE THREAD

**Issue by gopher333** [penk/penkesu#11]
Hi, I would appreciate a little more detail about the hardware configuration of the keyboard. How do I attach the Arduino Mini to the Keyboard (Pin Numbers)? I suppose the USB Port has to be to the outside of the PCB, but in which direction? USB side to the PCB or away from it? A picture would do...also the connection of the 4-pin usb connector would be helpfull (PINS?)
Tks is advance?

**Comment by 2disbetter** [comment]
![diodekb](https://user-images.githubusercontent.com/7128666/176251231-2b1e9734-dc02-40f5-abaf-e02de0ef30b5.jpg)
The micro usb port goes facing the Keyboard PCB. This picture should show you the pins. Be careful that nothing is touching metal on metal there. I actually put a small piece of kapton tape in between just to make sure. If you look at the picture showing the keyboard cable, you will see that the micro usb port is plugged in with a male micro usb connector. The two outer pins are your ground and power, and then you have your G+ and G- in the center. If you are making your own cable, jsut as long as the wires go to the same pin on the other connector, you'll be good. If you need more, just google a micro usb pin out, and that should fill in all the remaining questions.

**Comment by gopher333** [comment]
Thanks a lot for the immediate answer, that does it! Great project, by the way!!!
