### ISSUE TITLE
Keyboard Install

### ISSUE THREAD

**Issue by gopher333** [penk/penkesu#13]
Dear Penk, for your Keyboard Hex File-what Keyboard software installation did you use in Bullseye? I am from germany, tried the Keyboard on my windows Computer (works), but the keys have different values then.

**Comment by 2disbetter** [comment]
Hi again, I used the QMK Toolbox to flash the board. You merely grab that open it and then load the firmware you want to upload to the device, and then while shorting a pin on the board to enter flashing mode on the board, you connect it via USB. The Toolbox will find it and install the firmware automatically at that point. Wait for toolbox to tell you flashing is complete. Then you can unplug and plug the keyboard in to test the key functionality. It should respond as indicating on the readme page here.
