### ISSUE TITLE
More details for assembling PCB - diode and chip orientation, location?

### ISSUE THREAD

**Issue by CJ-eng** [penk/penkesu#15]
Hi Penk, 

Excellent project, I am in the process of assembling one. As I have not assemble a mechanical keyboard before, I wonder if you could provide more details on making the PCB. I am assuming the diode and the Pro Micro goes on the bottom side of PCB where as the key switch goes on the top side. Where does the diode goes exactly? And when soldering the Pro Micro, what’s the orientation? Would you provide a simple illustration or diagram? Thanks in advance.

**Comment by penk** [comment]
Hi @CJ-eng thanks for your interest in the project, for the build log I'd refer you to koda keyboard's creator and author :-) 

Hope this helps: 
https://oddrocketkeyboards.blogspot.com/2018/05/koda-keyboard-4x12-grid-using-kailh-lp.html
