### ISSUE TITLE
Need help to rotate the screen

### ISSUE THREAD

**Issue by CJ-eng** [penk/penkesu#16]
Hi Penk,

I've hooked up everything minus the keyboard (still waiting for PCB). However, for testing purpose, I hook up regular keyboard to Pi Zero's USB port. So everything works nicely except the default Waveshare screen is vertical. I edit the config.txt file as per Waveshare's Wiki page but it is not working :-(

Please let me know how to get the screen to rotate. Thanks!!!

**Comment by penk** [comment]
For the record it was set with xrandr commands. :-)

**Comment by CJ-eng** [comment]
Thanks for your reply. I have to delete everything else in the config.txt file and then the rotate command works. But I will try your command as well. I am enjoying the pencil case PC very much!
