### ISSUE TITLE
Where are the - and + key?

### ISSUE THREAD

**Issue by CJ-eng** [penk/penkesu#17]
Hi,

I have used your key map and I can't find the - and + key. I've searched  the "raise" layer or the "lower" layer. Please advises. Thanks.

**Comment by 2disbetter** [comment]
The minus (-) can be accessed via lower + h, and the plus (+) can be accessed via raise + j. Not that intuitive for sure but a small keyboard requires some compromises. BTW, is this CJ Engineering from Youtube, of Framework fame? If so hi, from the same person on the Framework forums.

**Comment by CJ-eng** [comment]
Thank you so much for fast response. Yes indeed the key is there, I was testing the keymap by mechanical keyboard tester online and somehow the key is not registered. But all is well now.

I am not familiar with the person you mentioned. The name is just coincidental.

Thanks and keep up the good work!
