### ISSUE TITLE
Os 

### ISSUE THREAD

**Issue by gedw99** [penk/penkesu#2]
You got slash dotted !

https://www.tomshardware.com/news/raspberry-pi-zero-2-w-penkesu-computer

Have you decided on an OS ?

gokrazy might be a good fit for super low resource device . I run it 

https://github.com/gokrazy

for apps you can use Fyne or gioui

https://github.com/fyne-io/fyne

https://github.com/gioui

I use gio cause it’s gives the most flexibility. It would not be hard to get it running with gio and the community would probably help you ! They are pro open source .

This makes it very lean and easy for you and others to build apps for it .

**Comment by gedw99** [comment]
Also AdGuard ad blocker is programmed in go so if you wanted to add a web browser it would be relatively easy to integrate AdGuard into it . 



gioui is similar to QT but

**Comment by gedw99** [comment]
https://gokrazy.org/platforms/#raspberry-pi-zero-2-w-work-in-progress

**Comment by penk** [comment]
@gedw99 thank you for your comments! Right now we are using Raspberry Pi OS Bullseye since it's working out-of-the-box. 

(btw I'm one of the author of cutiepi-shell so I'm flattered ;-)

**Comment by gedw99** [comment]
no worries.

**Comment by gedw99** [comment]
@penk when can i get my hands on the hardware ?
