### ISSUE TITLE
Re: PCB for Keyboard

### ISSUE THREAD

**Issue by michaeldvinci** [penk/penkesu#8]
This project is really cool, props!

I was wondering if you could flush out the README with more info as to how to order a version of the keyboard PCB? I've never tried ordering PCBs before and had no luck trying to find a fiscal way of getting it done. The only websites I could find to print custom PCBs wanted ~$60 to print 1x piece, so I was hoping maybe you had some good info on cheaper/decent pricing for ordering?

If there's a better place for this just let me know!

**Comment by cristicbz** [comment]
In the EU [Aisler](https://aisler.net/) makes reasonably priced boards, in the US people will typically pick [Oshpark](https://oshpark.com/) though I have no experience with them.

Generally, if you want cheap boards you have to with Chinese manufacturers and pay a bit more on shipping (assuming you're not in China). I used JLCPCB, uploaded gerber files, picked black soldermask, 1.6mm FR4, HASL Lead-free, and got some beautiful boards for ~$30 for 5 pcb-s including shipping.

For the actual assembly I found the blogpost that is ultimately linked form the readme (if you jump through a few links) very helpful: https://oddrocketkeyboards.blogspot.com/2018/05/koda-keyboard-4x12-grid-using-kailh-lp.html

See PCB and assembled board:
![PXL_20220408_222709936 MP](https://user-images.githubusercontent.com/801328/162542606-d677cdcd-0fff-47ed-9c39-9219f265eba2.jpg)
![PXL_20220408_222719584 MP](https://user-images.githubusercontent.com/801328/162542611-f48bdc23-cde9-4f62-939f-c930badd4ad9.jpg)
![PXL_20220408_222731638 MP](https://user-images.githubusercontent.com/801328/162542612-fad83591-1929-46a9-afb0-08c2ecaadff3.jpg)
