### ISSUE TITLE
Function keys?

### ISSUE THREAD

**Issue by cristicbz** [penk/penkesu#9]
Am I missing some obvious QMK magic? Or are there no bindings for F1...F12? I could send a patch for the layout, but dunno if I just missed the key combination to get a function keys

**Comment by 2disbetter** [comment]
The function keys are accessed via the Raise layer. Keys a,s,d,f,g,h and z,x,c,v,b,n are your F1 through F12 respectively. 👍

**Comment by cristicbz** [comment]
amazing, thank you!
